### ISSUE TITLE
Missing entry in `/etc/hosts`

### ISSUE THREAD

**Issue by jakubno** [e2b-dev/infra#70]
When running any sudo command, there's this line in the output:
```
user@fc1574dff44b:~$ sudo ls
> sudo: unable to resolve host fc1574dff44b: Name or service not known
```

**Comment by ValentaTomas** [comment]
This was caused by network config during image building — for now we changed this here https://github.com/e2b-dev/infra/blob/main/packages/env-build-task-driver/internal/env/rootfs.go#L293
